language: minimal
dist: xenial

matrix:
  include:
    - name: "Build for x86_64"
      env: ARCH=x86_64

    - name: "Build for i386"
      env: ARCH=i386

before_install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt-get update -q
  - sudo apt-get install flatpak-builder binutils elfutils git patch unzip -y

install:
  - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
  - flatpak install flathub-beta io.winebar.Platform//19.08beta io.winebar.Sdk//19.08beta

script: |
    flatpak-builder build-dir  --verbose \
      --install-deps-from=flathub-beta --user \
      --arch=$ARCH /dev/null \
      com.invisionapp.Studio.yml